apiVersion: v1
kind: Service
metadata:
  name: health-app-service
  namespace: health-demo
  labels:
    app: health-demo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: health-demo
---
apiVersion: v1
kind: Service
metadata:
  name: health-app-nodeport
  namespace: health-demo
  labels:
    app: health-demo
    type: external-access
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: health-demo
