# Pod Definition
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello-kubernetes
    version: v1
spec:
  containers:
  - name: hello-container
    image: nginxdemos/hello:plain-text
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
