# Service Definition
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-kubernetes
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: hello-kubernetes
