apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-operator
  namespace: webapp-operator-system
  labels:
    app: webapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-operator
  template:
    metadata:
      labels:
        app: webapp-operator
    spec:
      serviceAccountName: webapp-operator
      containers:
      - name: manager
        image: nginx:1.21
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 9443
          name: webhook-server
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "webapp-operator"
        volumeMounts:
        - name: operator-config
          mountPath: /usr/share/nginx/html
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: operator-config
        configMap:
          name: operator-config
      - name: webhook-certs
        secret:
          secretName: webhook-server-certs
          optional: true
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-operator-metrics
  namespace: webapp-operator-system
  labels:
    app: webapp-operator
spec:
  type: ClusterIP
  selector:
    app: webapp-operator
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-operator-webhook
  namespace: webapp-operator-system
  labels:
    app: webapp-operator
spec:
  type: ClusterIP
  selector:
    app: webapp-operator
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
