apiVersion: v1
kind: Secret
metadata:
  name: cluster-east-kubeconfig
  namespace: multi-cluster
  labels:
    cluster: east
type: Opaque
data:
  # Base64 encoded kubeconfig for east cluster
  kubeconfig: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiA8YmFzZTY0LWVuY29kZWQtY2EtY2VydD4KICAgIHNlcnZlcjogaHR0cHM6Ly9lYXN0LWNsdXN0ZXIuZXhhbXBsZS5jb206NjQ0MwogIG5hbWU6IGVhc3QtY2x1c3Rlcg==
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-west-kubeconfig
  namespace: multi-cluster
  labels:
    cluster: west
type: Opaque
data:
  # Base64 encoded kubeconfig for west cluster
  kubeconfig: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiA8YmFzZTY0LWVuY29kZWQtY2EtY2VydD4KICAgIHNlcnZlcjogaHR0cHM6Ly93ZXN0LWNsdXN0ZXIuZXhhbXBsZS5jb206NjQ0MwogIG5hbWU6IHdlc3QtY2x1c3Rlcg==
