apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-cluster-controller
  namespace: multi-cluster
  labels:
    app: multi-cluster-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-cluster-controller
  labels:
    app: multi-cluster-controller
rules:
- apiGroups: [""]
  resources: ["pods", "services", "namespaces", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["cluster.x-k8s.io"]
  resources: ["clusters", "machines", "machinesets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["applications", "appprojects"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-cluster-controller
  labels:
    app: multi-cluster-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-cluster-controller
subjects:
- kind: ServiceAccount
  name: multi-cluster-controller
  namespace: multi-cluster
