apiVersion: apps.example.com/v1
kind: WebApp
metadata:
  name: sample-frontend
  namespace: default
  labels:
    app: sample-frontend
spec:
  replicas: 3
  image: nginx:1.21
  port: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  ingress:
    enabled: true
    host: frontend.local
    tls: false
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilization: 70
---
apiVersion: apps.example.com/v1
kind: WebApp
metadata:
  name: api-backend
  namespace: default
  labels:
    app: api-backend
spec:
  replicas: 2
  image: httpd:2.4
  port: 80
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  ingress:
    enabled: false
  autoscaling:
    enabled: false
---
apiVersion: apps.example.com/v1
kind: WebApp
metadata:
  name: micro-service
  namespace: default
  labels:
    app: micro-service
    tier: backend
spec:
  replicas: 4
  image: nginx:1.20
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  ingress:
    enabled: true
    host: api.local
    tls: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 12
    targetCPUUtilization: 60
