apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: config-management
  labels:
    app: config-demo
type: Opaque
data:
  # Base64 encoded values
  database-password: cGFzc3dvcmQxMjM=  # password123
  api-key: YWJjZGVmZ2hpams=  # abcdefghijk
  secret-token: bXktc2VjcmV0LXRva2Vu  # my-secret-token
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: config-management
  labels:
    app: config-demo
type: kubernetes.io/tls
data:
  # These are dummy certificates for demo purposes
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
