apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: config-management
  labels:
    app: config-demo
spec:
  type: ClusterIP
  selector:
    app: config-demo
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
