# ConfigMap for Application Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: webapp
data:
  # Application configuration
  api_url: "http://localhost:3001"
  frontend_port: "3000"
  backend_port: "3001"
  environment: "development"
  log_level: "info"
  
  # Nginx configuration
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream frontend {
            server localhost:3000;
        }
        
        upstream backend {
            server localhost:3001;
        }
        
        server {
            listen 80;
            
            # Frontend routes
            location / {
                proxy_pass http://frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            # API routes
            location /api/ {
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            # Health check
            location /health {
                return 200 "OK";
                add_header Content-Type text/plain;
            }
        }
    }
  
  # Application properties file
  app.properties: |
    app.name=Multi-Container Web App
    app.version=1.0.0
    app.description=Demo application showing multi-container patterns
    
    # Database configuration (non-sensitive)
    db.host=localhost
    db.port=5432
    db.name=webapp_db
    
    # Feature flags
    feature.user_registration=true
    feature.advanced_analytics=false
