# Secret for Sensitive Application Data
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: webapp
type: Opaque
data:
  # Database credentials (base64 encoded)
  db_username: d2ViYXBwX3VzZXI=  # webapp_user
  db_password: c2VjdXJlUGFzc3dvcmQxMjM=  # securePassword123
  
  # API keys (base64 encoded)
  jwt_secret: bXlTdXBlclNlY3JldEp3dEtleUZvckF1dGg=  # mySuperSecretJwtKeyForAuth
  api_key: YWJjZGVmZ2hpamsxMjM0NTY3ODkw  # abcdefghijk1234567890
  
  # External service credentials
  redis_password: cmVkaXNQYXNzd29yZA==  # redisPassword
  
---
# Alternative: Create Secret from literal values
# This shows how you would create the same secret using kubectl
# kubectl create secret generic app-secrets \
#   --from-literal=db_username=webapp_user \
#   --from-literal=db_password=securePassword123 \
#   --from-literal=jwt_secret=mySuperSecretJwtKeyForAuth \
#   --from-literal=api_key=abcdefghijk1234567890 \
#   --from-literal=redis_password=redisPassword
