apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edge-agent
  namespace: edge-computing
  labels:
    app: edge-agent
spec:
  selector:
    matchLabels:
      app: edge-agent
  template:
    metadata:
      labels:
        app: edge-agent
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: edge-agent
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
          hostPort: 8080
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: EDGE_LOCATION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['location']
        volumeMounts:
        - name: edge-config
          mountPath: /usr/share/nginx/html
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        - name: host-sys
          mountPath: /host/sys
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          privileged: true
      volumes:
      - name: edge-config
        configMap:
          name: edge-agent-config
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-sys
        hostPath:
          path: /sys
      nodeSelector:
        edge-role: agent
      tolerations:
      - key: "edge"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: edge-agent-service
  namespace: edge-computing
  labels:
    app: edge-agent
spec:
  type: NodePort
  selector:
    app: edge-agent
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
