apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-reader
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-developer
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-admin
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: secure-namespace
