apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-alpha-quota
  namespace: tenant-alpha
  labels:
    tenant: alpha
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-beta-quota
  namespace: tenant-beta
  labels:
    tenant: beta
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-alpha-limits
  namespace: tenant-alpha
  labels:
    tenant: alpha
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-beta-limits
  namespace: tenant-beta
  labels:
    tenant: beta
spec:
  limits:
  - default:
      cpu: "250m"
      memory: "512Mi"
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
    type: Container
  - max:
      cpu: "1"
      memory: "2Gi"
    min:
      cpu: "25m"
      memory: "32Mi"
    type: Container
